// Auto-generated from RTO.xlsx — 35 states, 1051 districts
// Do not edit manually

export const STATES = ["Andaman & Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh", "Dadra & Nagar Haveli", "Daman and Diu", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu & Kashmir", "Jharkhand", "Karnataka", "Kerala", "Lakshadweep", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Orissa", "Pondicherry", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"]

export const STATE_DISTRICTS = {
  "Andaman & Nicobar Islands": [
    "Car Nicobar",
    "Port Blair"
  ],
  "Andhra Pradesh": [
    "Adilabad / Mancherial / Nirmal",
    "Anantapur / Hindupur",
    "Bahadurpura",
    "Bejawada / Gudivada / Machilipatnam / Nandigama",
    "Chittoor / Tirupati / Madanapalle / Rajampet",
    "Eluru / Jangareddygudem / Kovvur / Tadepalligudem / Tanuku / Bhimavaram / Palakollu / Chintalapudi",
    "Gajuwaka",
    "Guntur",
    "Guntur / Piduguralla / Narasaraopet / Repalle",
    "Kadapa / Proddatur",
    "Kakinada",
    "Kakinada / Amalapuram / Rajahmundry",
    "Karimnagar",
    "Karimnagar / Jagtial / Peddapalli",
    "Khairtabad",
    "Khammam / Kothagudem / Sathupally / Yellandu",
    "Kurnool / Adoni / Nandyal",
    "Mahaboobnagar / Pebbair / Gadwal",
    "Malakpet",
    "Medak / Siddipet / Sangareddy (RC puram)",
    "Mehdipatnam",
    "Nalgonda / Bhongir / Suryapet",
    "Nellore / Kavali / Gudur / Sullurpeta",
    "Nizamabad / Kamareddy",
    "Nuzvid",
    "Ongole / Chirala / Markapur / Prakasam",
    "Rangareddy",
    "Secunderabad",
    "Srikakulam /Tekkali /Palasa/Sompeta/Ichchapuram/Kaviti",
    "Visakhapatnam",
    "Visakhapatnam / Gajuwaka / Anakapalli",
    "Vizianagaram",
    "Warangal / Jangaon / Mahabubabad"
  ],
  "Arunachal Pradesh": [
    "Along",
    "Anini",
    "Bomdila",
    "Changlang",
    "Daporijo",
    "Itanagar",
    "Itanagar (commercial vehicles of state transport)",
    "Khonsa",
    "Pasighat",
    "Seppa",
    "Tawang",
    "Tezu",
    "Yingkiong",
    "Ziro"
  ],
  "Assam": [
    "Assam Police",
    "Assam Police vehicles",
    "Assam State Transport Corporation (ASTC)",
    "Barpeta",
    "Bongaigaon",
    "Cachar",
    "Darrang",
    "Dhemaji",
    "Dhubri",
    "Dibrugarh",
    "Dima Hasao",
    "Goalpara",
    "Golaghat",
    "Guwahati",
    "Guwahati no longer used",
    "Hailakandi",
    "Jorhat",
    "Karbi Anglong",
    "Karimganj",
    "Kokrajhar",
    "Lakhimpur district",
    "Marigaon",
    "Nagaon",
    "Nalbari",
    "Sibsagar",
    "Sonitpur",
    "Tinsukia",
    "Udalguri"
  ],
  "Bihar": [
    "(not allotted after Jharkhand Division)",
    "(not allotted)",
    "Araria",
    "Arwal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bettiah",
    "Bhabua",
    "Bhagalpur",
    "Bhojpur",
    "Buxar",
    "Chaibasa",
    "Chapra",
    "Darbhanga",
    "Dehri",
    "Gaya",
    "Giridih",
    "Gopalganj",
    "Jamui",
    "Jehanabad",
    "Katihar",
    "Khagaria",
    "Kishanganj",
    "Koderma",
    "Lakhisarai",
    "Madhepura",
    "Madhubani",
    "Motihari",
    "Munger",
    "Muzaffarpur",
    "Nalanda",
    "Nawada",
    "Patna",
    "Purnea",
    "Saharsa",
    "Samastipur",
    "Sheikhpura",
    "Sitamarhi",
    "Siwan",
    "Supaul",
    "Vaishali district"
  ],
  "Chandigarh": [
    "Chandigarh",
    "Chandigarh  Commercial Vehicles",
    "Chandigarh  Government Vehicles"
  ],
  "Chhattisgarh": [
    "Ambikapur",
    "Baikunthpur",
    "Bijapur",
    "Bilaspur",
    "Chattisgarh Police",
    "Dantewada",
    "Dhamtari",
    "Durg",
    "Government of Chattisgarh",
    "Governor of Chattisgarh",
    "Jagdalpur",
    "JanjgirChampa",
    "Jashpur",
    "Kanker",
    "Kawardha",
    "Korba",
    "Mahasamund",
    "Raigarh",
    "Raipur",
    "Rajnandgaon"
  ],
  "Dadra & Nagar Haveli": [
    "Silvassa"
  ],
  "Daman and Diu": [
    "Daman",
    "Diu"
  ],
  "Delhi": [
    "Central Delhi Central: Sarai Kale Khan",
    "Delhi North: Mall Road",
    "Delhi for auto rickshaws and radio taxis",
    "Delhi for commercial buses",
    "Delhi for commercial private taxis",
    "Delhi for commercial taxis",
    "Delhi for nonresident Indians",
    "Delhi for trucks",
    "East Delhi East 1: Mayur Vihar",
    "East Delhi II: Surajmal Vihar / Shahdara",
    "Faridabad due to the NCR",
    "Ghaziabad due to the NCR",
    "Gurgaon due to the NCR",
    "New Delhi: Tilak Marg",
    "Noida due to the NCR",
    "North East Delhi: Loni Road",
    "North West Delhi 1: Wazir Pur",
    "North West Delhi North West Zone II: Rohini",
    "Sonipat due to the NCR",
    "South Delhi South: Sheikh Sarai",
    "South West Delhi South West 1: Janakpuri / Palam",
    "South West Delhi South West II: Vasant Vihar",
    "West Delhi West 1: West Janakpuri",
    "West DelhiII: Raja Garden"
  ],
  "Goa": [
    "Bicholim",
    "Canacona",
    "Mapusa",
    "Margao",
    "Panaji",
    "Pernem",
    "Ponda",
    "Quepem",
    "Vasco da Gama"
  ],
  "Gujarat": [
    "Ahmedabad",
    "Amreli",
    "Anand",
    "Bardoli",
    "Bharuch",
    "Bhavnagar",
    "Dahod",
    "East Ahmedabad",
    "East Rajkot",
    "Gandhinagar",
    "Jamnagar",
    "Junagadh",
    "Kheda",
    "Kutch",
    "Mehsana",
    "Narmada",
    "Navsari",
    "Palanpur",
    "Panchmahal (Godhara)",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Sabarkantha",
    "Surat",
    "Surendranagar",
    "Vadodara",
    "Vadodara rural",
    "Valsad",
    "Vyara",
    "West Surat"
  ],
  "Haryana": [
    "(temporary numbers)",
    "Adampur",
    "Ambala  Barara",
    "Ambala (HR 01 GA for trucks; HR 01 PA",
    "Ambala (commercial vehicles only)",
    "Assandh",
    "Bahadurgarh",
    "Ballabgarh",
    "Barwala",
    "Beri",
    "Bhiwani",
    "Bhiwani (commercial vehicles only)",
    "Bilaspur",
    "Charkhi Dadri",
    "Dabwali",
    "Ellenabad",
    "Faridabad",
    "Faridabad (commercial vehicles only)",
    "Fatehabad",
    "Fatehabad (commercial vehicles only)",
    "Ferozepur Jhirka",
    "Ganaur",
    "Gohana",
    "Guhla",
    "Gurgaon",
    "Gurgaon (South)",
    "Gurgaon (commercial vehicles only)",
    "Hansi",
    "Hatin",
    "Hisar",
    "Hisar (commercial vehicles only)",
    "Hodal",
    "Indri",
    "Jagadhari",
    "Jhajjar",
    "Jhajjar (commercial vehicles only)",
    "Jind",
    "Jind (commercial vehicles only)",
    "Kaithal",
    "Kaithal (commercial vehicles only)",
    "Kalka",
    "Karnal",
    "Karnal (commercial vehicles only)",
    "Kharkhoda",
    "Kosli",
    "Kundli",
    "Kuru",
    "Kurukshetra (commercial vehicles only)",
    "Loharu",
    "Meham",
    "Mewat (Nuh)",
    "Mohindergarh",
    "Naraingarh",
    "Narnaul",
    "Narnaul (commercial vehicles only)",
    "Narwana",
    "Nuh",
    "Palwal",
    "Panchkula",
    "Panchkula (commercial vehicles only)",
    "Panipat",
    "Panipat (commercial vehicles only)",
    "Pataudi",
    "Pehowa",
    "Ratia",
    "Rewari",
    "Rewari (commercial vehicles only)",
    "Rohtak",
    "Rohtak (commercial vehicles only)",
    "Safidon",
    "Sahabad",
    "Samalkha",
    "Sirsa",
    "Sirsa (commercial vehicles only)",
    "Siwani",
    "Sonepat",
    "Sonipat",
    "Sonipat (commercial vehicles only)",
    "This series belongs to the Transport Commissioner in Chandigarh",
    "Tohana",
    "Tosham",
    "Yamuna Nagar"
  ],
  "Himachal Pradesh": [
    "Amb",
    "Anni",
    "Arki",
    "Baijnath",
    "Banjar",
    "Barsar",
    "Bharmour",
    "Bhoranj",
    "Bilaspur",
    "Chamba",
    "Chaupal",
    "Chowari",
    "Churah",
    "Dalhousie",
    "Dehra",
    "Dharamsala (autorikshaws)",
    "Dharamshala",
    "DodraKwar",
    "Ghumarwin",
    "Hamirpur",
    "Jaisinghpur",
    "Jawali",
    "Jogindernagar",
    "Kalpa",
    "Kandaghat",
    "Kangra",
    "Karsog",
    "Kaza",
    "Keylong",
    "Kullu",
    "Manali",
    "Mandi",
    "Mandi (autorikshaws)",
    "Nadaun / Hamirpur",
    "Nahan",
    "Nalagarh",
    "Nichar (Bhaba Nagar)",
    "Nurpur",
    "Paddhar",
    "Palampur",
    "Pangi",
    "Paonta Sahib",
    "Parwanoo",
    "Pooh",
    "Rajgarh",
    "Rampur Bushar",
    "Rohru",
    "Sarkaghat",
    "Shimla",
    "Shimla  Urban",
    "Shimla  Urban (tourist buses & taxis)",
    "Shimla (autorikshaws)",
    "Shimla (rural)",
    "Solan",
    "Sundernagar",
    "Theog",
    "Udaipur",
    "Una"
  ],
  "Jammu & Kashmir": [
    "Anantnag",
    "Bandipora",
    "Baramulla",
    "Budgam",
    "Doda",
    "Ganderbal",
    "Jammu",
    "Kargil",
    "Kathua",
    "Kishtwar",
    "Kulgam",
    "Kupwara",
    "Leh",
    "Poonch",
    "Pulwama",
    "Rajouri",
    "Ramban",
    "Reasi",
    "Samba",
    "Shopian",
    "Srinagar",
    "Udhampur"
  ],
  "Jharkhand": [
    "Bokaro Steel City",
    "Chaibasa",
    "Chatra",
    "Daltonganj",
    "Deoghar",
    "Dhanbad",
    "Dumka",
    "Garhwa",
    "Giridih",
    "Godda",
    "Gumla",
    "Hazaribagh / Ramgarh",
    "Jamshedpur",
    "Jamtara",
    "Koderma",
    "Latehar",
    "Lohardaga",
    "Pakur",
    "Ranchi",
    "Sahibganj",
    "SaraikelaKharsawan",
    "Simdega"
  ],
  "Karnataka": [
    "Bagalkot",
    "Bailhongal",
    "Bangalore Central (Koramangala)",
    "Bangalore East (Indiranagar)",
    "Bangalore North (Yeshwanthpur)",
    "Bangalore South (Jayanagar)]]",
    "Bangalore West (Rajajinagar)",
    "Basavakalyan",
    "Belgaum",
    "Bellary",
    "Bhalki",
    "Bidar",
    "Bijapur",
    "Chamrajnagar",
    "Chickmagalur",
    "Chikkaballapur",
    "Chikkodi",
    "Chitradurga",
    "Davangere",
    "Devanahalli",
    "Dharwad",
    "Electronics City",
    "Gadag",
    "Gokak",
    "Gulbarga",
    "Hassan",
    "Haveri",
    "Honnavar",
    "Hospet",
    "Hunsur",
    "Jamkhandi",
    "K.R. Puram",
    "Karwar",
    "Kolar",
    "Kolar Gold Fields (KGF)",
    "Koppal",
    "Madikeri",
    "Mandya",
    "Mangalore",
    "Mysore East",
    "Mysore West",
    "Nagamangala",
    "Nelamangala",
    "Puttur / Sullia",
    "Raichur",
    "Rajarajeshwari Nagar",
    "Ramanagara",
    "Sagara",
    "Sakleshpur",
    "Shantinagar",
    "Shimoga",
    "Sirsi",
    "Tiptur",
    "Tumkur",
    "Udupi",
    "Yadgir",
    "Yelahanka"
  ],
  "Kerala": [
    "Adoor",
    "Alappuzha",
    "Alathur",
    "Aluva",
    "Angamaly",
    "Chalakkudy",
    "Changanassery",
    "Chengannur",
    "Cherthala",
    "Eranakulam",
    "Guruvayur",
    "Idukki",
    "Irinjalakuda",
    "Kanhangad",
    "Kanjirappally",
    "Kannur",
    "Karunagapally",
    "Kasargode",
    "Kayamkulam",
    "Kazhakkoottam",
    "Kodungallur",
    "Koduvally",
    "Kollam",
    "Kottarakara",
    "Kottayam",
    "Koyilandi",
    "Kozhikode",
    "Kunnathur",
    "Malappuram",
    "Mallappally",
    "Mannarghat",
    "Mattancherry",
    "Mavelikara",
    "Muvattupuzha",
    "North Paravur",
    "Ottappalam",
    "Pala",
    "Palakkad",
    "Pathanamthitta",
    "Pattambi",
    "Perinthalmanna",
    "Perumbavoor",
    "Ponnani",
    "Punalur",
    "Ranni",
    "Thalassery",
    "Thaliparamba",
    "Thirurangadi",
    "Thiruvalla",
    "Thiruvananthapuram (Kerala State Road Transport Corporation buses)",
    "Thiruvananthapuram City",
    "ThiruvananthapuramAttingal",
    "ThiruvananthapuramNedumangad",
    "ThiruvananthapuramNeyyattinkara",
    "ThiruvananthapuramParassala",
    "Thodupuzha",
    "Thripunithura",
    "Thrissur",
    "Tirur",
    "Vadakara",
    "Vaikom",
    "Vandiperiyar",
    "Wadakkancherry",
    "Wayanad",
    "kothamangalam"
  ],
  "Lakshadweep": [
    "Kavaratti"
  ],
  "Madhya Pradesh": [
    "(not alloted)",
    "Alirajpur (upcoming)",
    "Ambikapur (not in use)",
    "Anoopur",
    "Ashoknagar",
    "Badwani",
    "Balaghat",
    "Betul",
    "Bhind",
    "Bhopal",
    "Bilaspur (not in use)",
    "Burhanpur",
    "Chhatarpur",
    "Chhindwara",
    "Damoh",
    "Datia",
    "Dewas",
    "Dhar",
    "Dindori",
    "Durg (not in use)",
    "Guna",
    "Gwalior",
    "Harda",
    "Hoshangabad",
    "Indore",
    "Jabalpur",
    "Jagdalpur (not in use)",
    "Jhabua",
    "Katni",
    "Khandwa",
    "Khargone",
    "M.P. Government Vehicle",
    "M.P. Police Vehicle",
    "Mandla",
    "Mandsaur",
    "Morena",
    "Narsinghpur",
    "Neemuch",
    "Panna",
    "Raipur (not in use)",
    "Raisen",
    "Rajgarh",
    "Rajnandgaon (not in use)",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Seoni",
    "Shahdol",
    "Shajapur",
    "Sheopur",
    "Shivpuri",
    "Sidhi",
    "Singrauli",
    "State Governor's Vehicle",
    "Tikamgarh",
    "Ujjain",
    "Umariya",
    "Vidisha",
    "not in use"
  ],
  "Maharashtra": [
    "Ahmednagar",
    "Akluj",
    "Akola",
    "Ambejogai",
    "Amravati",
    "Aurangabad",
    "Baramati",
    "Beed",
    "Bhandara",
    "Borivali",
    "Buldana",
    "Chandrapur",
    "Dhule",
    "Gadchiroli",
    "Gondia",
    "Hingoli",
    "Jalgaon",
    "Jalna",
    "Karad (Satara Rural)  RTO is located in Karad",
    "Kolhapur",
    "Latur",
    "Malegaon",
    "Mumbai (Central)  RTO is located in Tardeo",
    "Mumbai (East)  RTO is located in Wadala",
    "Mumbai (West)  RTO is located in Andheri West",
    "Nagpur",
    "Nagpur (East)  RTO is located on Bhandara Road",
    "Nanded",
    "Nandurbar",
    "Nashik",
    "Navi Mumbai  RTO is located in Vashi (Sanpada)",
    "Osmanabad",
    "Panvel",
    "Parbhani",
    "Pune",
    "Pune (Outskirts)  RTO is located in PimpriChinchwad",
    "Raigad  RTO is located in Pen (does not include Navi Mumbai",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Shrirampur",
    "Sindhudurg",
    "Solapur",
    "Thane",
    "Thane (Central Suburbs): Kalyan",
    "Vasai Thane (Western Suburbs from Vasai)  RTO is located in Virar",
    "Wadi",
    "Wardha",
    "Washim",
    "Yavatmal  RTO is located on Nagpur Road"
  ],
  "Manipur": [
    "Churachandpur",
    "Imphal",
    "Kangpokpi",
    "Thoubal"
  ],
  "Meghalaya": [
    "East Garo Hills",
    "East Khasi Hills",
    "Jaintia Hills",
    "RiBhoi",
    "Shillong (government vehicles)",
    "Shillong (police vehicles)",
    "Shillong (vehicles owned by transport corporations)",
    "South Garo Hills",
    "West Garo Hills",
    "West Khasi Hills"
  ],
  "Mizoram": [
    "Aizawl",
    "Champhai",
    "Kolasib",
    "Lawngtlai",
    "Lunglei",
    "Mamit",
    "Saiha",
    "Serchhip"
  ],
  "Nagaland": [
    "Dimapur",
    "Kohima",
    "Mokokchung",
    "Mon",
    "Phek",
    "Tuensang",
    "Wokha",
    "Zunheboto"
  ],
  "Orissa": [
    "Angul",
    "Balasore",
    "Baragarh",
    "Bhadrak",
    "Bhubaneswar",
    "Bolangir",
    "Boudh",
    "Chandikhole",
    "Cuttack",
    "Debagarh",
    "Dhenkanal",
    "Gajapati",
    "Ganjam",
    "Jagatsinghpur",
    "Jharsuguda",
    "Kalahandi",
    "Kendarapara",
    "Keonjhar",
    "Koraput",
    "Malkangiri",
    "Mayurbhanj",
    "Nabarangpur",
    "Nayagarh",
    "Nuapada",
    "Phulabani",
    "Puri",
    "Rayagada",
    "Rourkela",
    "Sambalpur",
    "Sonepur",
    "Sundergarh"
  ],
  "Pondicherry": [
    "Karaikal",
    "Mahe",
    "Pondicherry",
    "Yanam"
  ],
  "Punjab": [
    "Abohar",
    "Ajnala",
    "Amloh",
    "Amritsar",
    "Anandpur Sahib",
    "Baba Bakala",
    "Bagha Purana",
    "Balachaur",
    "Barnala",
    "Bassi Pathana",
    "Batala",
    "Bathinda",
    "Bhulath",
    "Budhlada",
    "Chamkaur Sahib",
    "Dasua",
    "Dera Baba Nanak",
    "Dera Bassi",
    "Dhar",
    "Dhuri",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Ferozepur",
    "Garhshankar",
    "Gidderbaha",
    "Gurdaspur",
    "Hoshiarpur",
    "Jagraon",
    "Jaitu",
    "Jalalabad",
    "Jalandhar",
    "Jhunir / Sardulgarh",
    "Kapurthala",
    "Khadoor Sahib",
    "Khamano",
    "Khanna",
    "Kharar",
    "Lehra",
    "Ludhiana",
    "Malerkotla",
    "Malout",
    "Mansa",
    "Moga",
    "Mohali",
    "Moonak",
    "Mukerian",
    "Muktsar",
    "Nabha",
    "Nakodar",
    "Nangal",
    "Nawanshahr",
    "Nihal Singh Wala",
    "Pathankot",
    "Patiala",
    "Patran",
    "Patti",
    "Payal",
    "Phagwara",
    "Phillaur",
    "Raikot",
    "Rajpura",
    "Rampura Phul",
    "Ropar",
    "Samana",
    "Samrala",
    "Sangrur",
    "Shahkot",
    "Sultanpur Lodhi",
    "Sunam",
    "Talwandi Sabo",
    "Tappa Mandi",
    "Tarn Taran",
    "Taxis",
    "Zira"
  ],
  "Rajasthan": [
    "Ajmer",
    "Alwar",
    "Banswara",
    "Baran",
    "Barmer",
    "Beawar",
    "Bharatpur",
    "Bhilwara",
    "Bikaner",
    "Bundi",
    "Chittaurgarh",
    "Churu",
    "Dausa",
    "Dholpur",
    "Didwana",
    "Dungarpur",
    "Hanumangarh",
    "Jaipur",
    "Jaisalmer",
    "Jalore",
    "Jhalawar",
    "Jhunjhunu",
    "Jodhpur",
    "Karauli",
    "Kota",
    "Kotputli",
    "Nagaur",
    "Pali",
    "Pratapgarh",
    "Rajsamand",
    "Ramganj Mandi",
    "Rawhhuu",
    "Sawai Madhopur",
    "Sikar",
    "Sirohi",
    "Sri Ganganagar",
    "Tonk",
    "Udaipur"
  ],
  "Sikkim": [
    "Gangtok",
    "Gyalshing",
    "Jorethang",
    "Mangan"
  ],
  "Tamil Nadu": [
    "Ariyalur",
    "Attur",
    "Chengalpattu",
    "Chennai Central (Ayanavaram)",
    "Chennai East (Basin Bridge)",
    "Chennai North (Vyasarpadi)",
    "Chennai North East (Tondiarpet)",
    "Chennai South (Thiruvanmiyur)",
    "Chennai South East (Mandaveli)",
    "Chennai South West (Valasarawakkam)",
    "Chennai West (Anna Nagar)",
    "Chennai West (K.K. Nagar)",
    "Coimbatore (Central)",
    "Coimbatore (North)",
    "Coimbatore (South)",
    "Cuddalore",
    "Dharapuram",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Gobichettipalayam",
    "Hosur",
    "Kanchipuram",
    "Karur",
    "Krishnagiri",
    "Kumbakonam",
    "Madurai (Central)",
    "Madurai (North)",
    "Madurai (South)",
    "Marthandam",
    "Meenambakkam",
    "Mettupalayam",
    "Nagapattinam",
    "Nagercoil",
    "Namakkal",
    "Perambalur",
    "Perundurai",
    "Pollachi",
    "Pudukottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem (East)",
    "Salem (West)",
    "Sankagiri",
    "Sengundram",
    "Sivagangai",
    "Srirangam (Tiruchirapalli)",
    "State Government Vehicles",
    "State Transport Undertakings",
    "Tambaram",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thiruchengode",
    "Thiruvannamalai",
    "Tindivanam",
    "Tiruchirapalli",
    "Tirunelveli",
    "Tirupur (North)",
    "Tirupur (South)",
    "Tiruvallur",
    "Tiruvarur",
    "Tuticorin",
    "Uthagamandalam",
    "Vellore",
    "Villupuram",
    "Virudhunagar"
  ],
  "Tripura": [
    "Agartala",
    "Kailashahar",
    "Udaipura"
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Allahabad",
    "Almora (not longer in use)",
    "Ambedkar Nagar",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Azamgarh for commercial vehicles",
    "Azamgarh for government vehicles",
    "Badaun",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Bulandshahr",
    "Chamoli (not longer in use)",
    "Chandauli",
    "Chitrakoot Dham (Karwi)",
    "Dehradun (not longer in use)",
    "Deoria",
    "Etah",
    "Etawah",
    "Etawah for government vehicles",
    "Faizabad",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur for commercial vehicles",
    "Gorakhpur for government vehicles",
    "Gorakhpur for private vehicles",
    "Haldwani (not longer in useï¿½?)",
    "Hamirpur",
    "Hapur",
    "Hardoi",
    "Haridwar (not longer in use)",
    "Jalaun",
    "Jaunpur",
    "Jaunpur for taxis",
    "Jhansi",
    "Jhansi for government vehicles",
    "Jhansi for public transport",
    "Jyotiba Phule Nagar",
    "Kannauj",
    "Kanpur  Urban",
    "Kanpur CNG Vehicles",
    "Kanpur Dehat (rural)",
    "Kanpur Government Vehicles",
    "Kanshiram Nagar",
    "Kaushambi",
    "Kheri",
    "Lalitpur",
    "Lucknow",
    "Lucknow (when UP32 will be exhausted)",
    "Mahamaya Nagar",
    "Mahoba",
    "Mahoba for commercial vehicles",
    "Mahoba for government vehicles",
    "Mahrajganj",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut (UP15AT for taxis",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "NOIDA / Gautam Buddha Nagar",
    "Padrauna",
    "Pauri (not longer in use)",
    "Pilibhit",
    "Pithoragarh (not longer in use)",
    "Prabudh Nagar",
    "Pratapgarh",
    "Raebareli",
    "Raebareli for commercial vehicles",
    "Raebareli for government vehicles",
    "Rampur",
    "Saharanpur",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shrawasti",
    "Siddharth Nagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Tehri (not longer in use)",
    "Udham Singh Nagar (not longer in use)",
    "Unnao",
    "Unnao for commercial vehicles",
    "Uttarkashi (not longer in use)",
    "Varanasi",
    "to be alloted"
  ],
  "Uttarakhand": [
    "Almora",
    "Bageshwar",
    "Chamoli",
    "Champawat",
    "Dehra Dun (UK07TC for taxis)",
    "Haridwar",
    "Nanital",
    "Pauri",
    "Pithoragarh",
    "Rudraprayag",
    "Tehri",
    "Udham Singh Nagar",
    "Uttarkashi"
  ],
  "West Bengal": [
    "Alipurduar (other than transport vehicles)",
    "Alipurduar (transport vehicles)",
    "Asansol (other than transport vehicles)",
    "Asansol (transport vehicles)",
    "Balurghat (other than transport vehicles)",
    "Balurghat (transport vehicles)",
    "Bankura (other than transport vehicles)",
    "Bankura (transport vehicles)",
    "Barasat (other than transport vehicles)",
    "Barasat (transport vehicles)",
    "Barrackpore (other than transport vehicles)",
    "Barrackpore (transport vehicles)",
    "Birbhum (other than transport vehicles)",
    "Birbhum (transport vehicles)",
    "Burdwan (other than transport vehicles)",
    "Burdwan (transport vehicles)",
    "Contai (other than transport vehicles)",
    "Contai (transport vehicles)",
    "Cooch Behar (other than transport vehicles)",
    "Cooch Behar (transport vehicles)",
    "Darjeeling (other than transport vehicles)",
    "Darjeeling (transport vehicles)",
    "Durgapur (other than transport vehicles)",
    "Durgapur (transport vehicles)",
    "Hooghly (other than transport vehicles)",
    "Hooghly (other than transport vehicles)  exhausted",
    "Hooghly (transport vehicles)",
    "Howrah  to be used",
    "Howrah (other than transport vehicles)",
    "Howrah (other than transport vehicles)  till WB14 K",
    "Howrah (transport vehicles)",
    "Jalpaiguri (other than transport vehicles)",
    "Jalpaiguri (transport vehicles)",
    "Kalimpong (other than transport vehicles)",
    "Kalimpong (transport vehicles)",
    "Kolkata  to be used",
    "Kolkata (goods carriages)",
    "Kolkata (passenger vehicles)",
    "Kolkata (private fourwheelers)",
    "Kolkata (tractors",
    "Kolkata (twowheelers)",
    "Kolkata (twowheelers)  exhausted",
    "Malda (other than transport vehicles)",
    "Malda (transport vehicles)",
    "Midnapur (other than transport vehicles)",
    "Midnapur (transport vehicles)",
    "Murshidabad (other than transport vehicles)",
    "Murshidabad (transport vehicles)",
    "Nadia (other than transport vehicles)",
    "Nadia (transport vehicles)",
    "Purulia (other than transport vehicles)",
    "Purulia (transport vehicles)",
    "Raiganj (other than transport vehicles)",
    "Raiganj (transport vehicles)",
    "Siliguri (other than transport vehicles)",
    "Siliguri (transport vehicles)",
    "South 24 Parganas",
    "Tamluk (other than transport vehicles)",
    "Tamluk (transport vehicles)"
  ]
}

export function getDistricts(state) {
  return STATE_DISTRICTS[state] || []
}
