import dotenv from 'dotenv'
dotenv.config()
import sequelize from './database.js'
import { District } from '../models/index.js'

async function run() {
  try {
    await sequelize.authenticate()
    console.log('✅ Connected to database')

    const existing = await District.count()
    console.log(`📊 Existing districts: ${existing}`)

    const districts = [
  { name: 'Car Nicobar', code: 'D0001', state: 'Andaman & Nicobar Islands', status: 'ACTIVE' },
  { name: 'Port Blair', code: 'D0002', state: 'Andaman & Nicobar Islands', status: 'ACTIVE' },
  { name: 'Adilabad / Mancherial / Nirmal', code: 'D0003', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Anantapur / Hindupur', code: 'D0004', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Bahadurpura', code: 'D0005', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Bejawada / Gudivada / Machilipatnam / Nandigama', code: 'D0006', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Chittoor / Tirupati / Madanapalle / Rajampet', code: 'D0007', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Eluru / Jangareddygudem / Kovvur / Tadepalligudem / Tanuku / Bhimavaram / Palakollu / Chintalapudi', code: 'D0008', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Gajuwaka', code: 'D0009', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Guntur', code: 'D0010', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Guntur / Piduguralla / Narasaraopet / Repalle', code: 'D0011', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Kadapa / Proddatur', code: 'D0012', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Kakinada', code: 'D0013', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Kakinada / Amalapuram / Rajahmundry', code: 'D0014', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Karimnagar', code: 'D0015', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Karimnagar / Jagtial / Peddapalli', code: 'D0016', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Khairtabad', code: 'D0017', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Khammam / Kothagudem / Sathupally / Yellandu', code: 'D0018', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Kurnool / Adoni / Nandyal', code: 'D0019', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Mahaboobnagar / Pebbair / Gadwal', code: 'D0020', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Malakpet', code: 'D0021', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Medak / Siddipet / Sangareddy (RC puram)', code: 'D0022', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Mehdipatnam', code: 'D0023', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Nalgonda / Bhongir / Suryapet', code: 'D0024', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Nellore / Kavali / Gudur / Sullurpeta', code: 'D0025', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Nizamabad / Kamareddy', code: 'D0026', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Nuzvid', code: 'D0027', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Ongole / Chirala / Markapur / Prakasam', code: 'D0028', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Rangareddy', code: 'D0029', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Secunderabad', code: 'D0030', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Srikakulam /Tekkali /Palasa/Sompeta/Ichchapuram/Kaviti', code: 'D0031', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Visakhapatnam', code: 'D0032', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Visakhapatnam / Gajuwaka / Anakapalli', code: 'D0033', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Vizianagaram', code: 'D0034', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Warangal / Jangaon / Mahabubabad', code: 'D0035', state: 'Andhra Pradesh', status: 'ACTIVE' },
  { name: 'Along', code: 'D0036', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Anini', code: 'D0037', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Bomdila', code: 'D0038', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Changlang', code: 'D0039', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Daporijo', code: 'D0040', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Itanagar', code: 'D0041', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Itanagar (commercial vehicles of state transport)', code: 'D0042', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Khonsa', code: 'D0043', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Pasighat', code: 'D0044', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Seppa', code: 'D0045', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Tawang', code: 'D0046', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Tezu', code: 'D0047', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Yingkiong', code: 'D0048', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Ziro', code: 'D0049', state: 'Arunachal Pradesh', status: 'ACTIVE' },
  { name: 'Assam Police', code: 'D0050', state: 'Assam', status: 'ACTIVE' },
  { name: 'Assam Police vehicles', code: 'D0051', state: 'Assam', status: 'ACTIVE' },
  { name: 'Assam State Transport Corporation (ASTC)', code: 'D0052', state: 'Assam', status: 'ACTIVE' },
  { name: 'Barpeta', code: 'D0053', state: 'Assam', status: 'ACTIVE' },
  { name: 'Bongaigaon', code: 'D0054', state: 'Assam', status: 'ACTIVE' },
  { name: 'Cachar', code: 'D0055', state: 'Assam', status: 'ACTIVE' },
  { name: 'Darrang', code: 'D0056', state: 'Assam', status: 'ACTIVE' },
  { name: 'Dhemaji', code: 'D0057', state: 'Assam', status: 'ACTIVE' },
  { name: 'Dhubri', code: 'D0058', state: 'Assam', status: 'ACTIVE' },
  { name: 'Dibrugarh', code: 'D0059', state: 'Assam', status: 'ACTIVE' },
  { name: 'Dima Hasao', code: 'D0060', state: 'Assam', status: 'ACTIVE' },
  { name: 'Goalpara', code: 'D0061', state: 'Assam', status: 'ACTIVE' },
  { name: 'Golaghat', code: 'D0062', state: 'Assam', status: 'ACTIVE' },
  { name: 'Guwahati', code: 'D0063', state: 'Assam', status: 'ACTIVE' },
  { name: 'Guwahati no longer used', code: 'D0064', state: 'Assam', status: 'ACTIVE' },
  { name: 'Hailakandi', code: 'D0065', state: 'Assam', status: 'ACTIVE' },
  { name: 'Jorhat', code: 'D0066', state: 'Assam', status: 'ACTIVE' },
  { name: 'Karbi Anglong', code: 'D0067', state: 'Assam', status: 'ACTIVE' },
  { name: 'Karimganj', code: 'D0068', state: 'Assam', status: 'ACTIVE' },
  { name: 'Kokrajhar', code: 'D0069', state: 'Assam', status: 'ACTIVE' },
  { name: 'Lakhimpur district', code: 'D0070', state: 'Assam', status: 'ACTIVE' },
  { name: 'Marigaon', code: 'D0071', state: 'Assam', status: 'ACTIVE' },
  { name: 'Nagaon', code: 'D0072', state: 'Assam', status: 'ACTIVE' },
  { name: 'Nalbari', code: 'D0073', state: 'Assam', status: 'ACTIVE' },
  { name: 'Sibsagar', code: 'D0074', state: 'Assam', status: 'ACTIVE' },
  { name: 'Sonitpur', code: 'D0075', state: 'Assam', status: 'ACTIVE' },
  { name: 'Tinsukia', code: 'D0076', state: 'Assam', status: 'ACTIVE' },
  { name: 'Udalguri', code: 'D0077', state: 'Assam', status: 'ACTIVE' },
  { name: '(not allotted after Jharkhand Division)', code: 'D0078', state: 'Bihar', status: 'ACTIVE' },
  { name: '(not allotted)', code: 'D0079', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Araria', code: 'D0080', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Arwal', code: 'D0081', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Aurangabad', code: 'D0082', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Banka', code: 'D0083', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Begusarai', code: 'D0084', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Bettiah', code: 'D0085', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Bhabua', code: 'D0086', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Bhagalpur', code: 'D0087', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Bhojpur', code: 'D0088', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Buxar', code: 'D0089', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Chaibasa', code: 'D0090', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Chapra', code: 'D0091', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Darbhanga', code: 'D0092', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Dehri', code: 'D0093', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Gaya', code: 'D0094', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Giridih', code: 'D0095', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Gopalganj', code: 'D0096', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Jamui', code: 'D0097', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Jehanabad', code: 'D0098', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Katihar', code: 'D0099', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Khagaria', code: 'D0100', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Kishanganj', code: 'D0101', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Koderma', code: 'D0102', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Lakhisarai', code: 'D0103', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Madhepura', code: 'D0104', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Madhubani', code: 'D0105', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Motihari', code: 'D0106', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Munger', code: 'D0107', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Muzaffarpur', code: 'D0108', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Nalanda', code: 'D0109', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Nawada', code: 'D0110', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Patna', code: 'D0111', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Purnea', code: 'D0112', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Saharsa', code: 'D0113', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Samastipur', code: 'D0114', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Sheikhpura', code: 'D0115', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Sitamarhi', code: 'D0116', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Siwan', code: 'D0117', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Supaul', code: 'D0118', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Vaishali district', code: 'D0119', state: 'Bihar', status: 'ACTIVE' },
  { name: 'Chandigarh', code: 'D0120', state: 'Chandigarh', status: 'ACTIVE' },
  { name: 'Chandigarh  Commercial Vehicles', code: 'D0121', state: 'Chandigarh', status: 'ACTIVE' },
  { name: 'Chandigarh  Government Vehicles', code: 'D0122', state: 'Chandigarh', status: 'ACTIVE' },
  { name: 'Ambikapur', code: 'D0123', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Baikunthpur', code: 'D0124', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Bijapur', code: 'D0125', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Bilaspur', code: 'D0126', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Chattisgarh Police', code: 'D0127', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Dantewada', code: 'D0128', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Dhamtari', code: 'D0129', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Durg', code: 'D0130', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Government of Chattisgarh', code: 'D0131', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Governor of Chattisgarh', code: 'D0132', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Jagdalpur', code: 'D0133', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'JanjgirChampa', code: 'D0134', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Jashpur', code: 'D0135', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Kanker', code: 'D0136', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Kawardha', code: 'D0137', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Korba', code: 'D0138', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Mahasamund', code: 'D0139', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Raigarh', code: 'D0140', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Raipur', code: 'D0141', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Rajnandgaon', code: 'D0142', state: 'Chhattisgarh', status: 'ACTIVE' },
  { name: 'Silvassa', code: 'D0143', state: 'Dadra & Nagar Haveli', status: 'ACTIVE' },
  { name: 'Daman', code: 'D0144', state: 'Daman and Diu', status: 'ACTIVE' },
  { name: 'Diu', code: 'D0145', state: 'Daman and Diu', status: 'ACTIVE' },
  { name: 'Central Delhi Central: Sarai Kale Khan', code: 'D0146', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Delhi North: Mall Road', code: 'D0147', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Delhi for auto rickshaws and radio taxis', code: 'D0148', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Delhi for commercial buses', code: 'D0149', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Delhi for commercial private taxis', code: 'D0150', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Delhi for commercial taxis', code: 'D0151', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Delhi for nonresident Indians', code: 'D0152', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Delhi for trucks', code: 'D0153', state: 'Delhi', status: 'ACTIVE' },
  { name: 'East Delhi East 1: Mayur Vihar', code: 'D0154', state: 'Delhi', status: 'ACTIVE' },
  { name: 'East Delhi II: Surajmal Vihar / Shahdara', code: 'D0155', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Faridabad due to the NCR', code: 'D0156', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Ghaziabad due to the NCR', code: 'D0157', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Gurgaon due to the NCR', code: 'D0158', state: 'Delhi', status: 'ACTIVE' },
  { name: 'New Delhi: Tilak Marg', code: 'D0159', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Noida due to the NCR', code: 'D0160', state: 'Delhi', status: 'ACTIVE' },
  { name: 'North East Delhi: Loni Road', code: 'D0161', state: 'Delhi', status: 'ACTIVE' },
  { name: 'North West Delhi 1: Wazir Pur', code: 'D0162', state: 'Delhi', status: 'ACTIVE' },
  { name: 'North West Delhi North West Zone II: Rohini', code: 'D0163', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Sonipat due to the NCR', code: 'D0164', state: 'Delhi', status: 'ACTIVE' },
  { name: 'South Delhi South: Sheikh Sarai', code: 'D0165', state: 'Delhi', status: 'ACTIVE' },
  { name: 'South West Delhi South West 1: Janakpuri / Palam', code: 'D0166', state: 'Delhi', status: 'ACTIVE' },
  { name: 'South West Delhi South West II: Vasant Vihar', code: 'D0167', state: 'Delhi', status: 'ACTIVE' },
  { name: 'West Delhi West 1: West Janakpuri', code: 'D0168', state: 'Delhi', status: 'ACTIVE' },
  { name: 'West DelhiII: Raja Garden', code: 'D0169', state: 'Delhi', status: 'ACTIVE' },
  { name: 'Bicholim', code: 'D0170', state: 'Goa', status: 'ACTIVE' },
  { name: 'Canacona', code: 'D0171', state: 'Goa', status: 'ACTIVE' },
  { name: 'Mapusa', code: 'D0172', state: 'Goa', status: 'ACTIVE' },
  { name: 'Margao', code: 'D0173', state: 'Goa', status: 'ACTIVE' },
  { name: 'Panaji', code: 'D0174', state: 'Goa', status: 'ACTIVE' },
  { name: 'Pernem', code: 'D0175', state: 'Goa', status: 'ACTIVE' },
  { name: 'Ponda', code: 'D0176', state: 'Goa', status: 'ACTIVE' },
  { name: 'Quepem', code: 'D0177', state: 'Goa', status: 'ACTIVE' },
  { name: 'Vasco da Gama', code: 'D0178', state: 'Goa', status: 'ACTIVE' },
  { name: 'Ahmedabad', code: 'D0179', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Amreli', code: 'D0180', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Anand', code: 'D0181', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Bardoli', code: 'D0182', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Bharuch', code: 'D0183', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Bhavnagar', code: 'D0184', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Dahod', code: 'D0185', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'East Ahmedabad', code: 'D0186', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'East Rajkot', code: 'D0187', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Gandhinagar', code: 'D0188', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Jamnagar', code: 'D0189', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Junagadh', code: 'D0190', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Kheda', code: 'D0191', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Kutch', code: 'D0192', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Mehsana', code: 'D0193', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Narmada', code: 'D0194', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Navsari', code: 'D0195', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Palanpur', code: 'D0196', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Panchmahal (Godhara)', code: 'D0197', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Patan', code: 'D0198', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Porbandar', code: 'D0199', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Rajkot', code: 'D0200', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Sabarkantha', code: 'D0201', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Surat', code: 'D0202', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Surendranagar', code: 'D0203', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Vadodara', code: 'D0204', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Vadodara rural', code: 'D0205', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Valsad', code: 'D0206', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'Vyara', code: 'D0207', state: 'Gujarat', status: 'ACTIVE' },
  { name: 'West Surat', code: 'D0208', state: 'Gujarat', status: 'ACTIVE' },
  { name: '(temporary numbers)', code: 'D0209', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Adampur', code: 'D0210', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Ambala  Barara', code: 'D0211', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Ambala (HR 01 GA for trucks; HR 01 PA', code: 'D0212', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Ambala (commercial vehicles only)', code: 'D0213', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Assandh', code: 'D0214', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Bahadurgarh', code: 'D0215', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Ballabgarh', code: 'D0216', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Barwala', code: 'D0217', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Beri', code: 'D0218', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Bhiwani', code: 'D0219', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Bhiwani (commercial vehicles only)', code: 'D0220', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Bilaspur', code: 'D0221', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Charkhi Dadri', code: 'D0222', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Dabwali', code: 'D0223', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Ellenabad', code: 'D0224', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Faridabad', code: 'D0225', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Faridabad (commercial vehicles only)', code: 'D0226', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Fatehabad', code: 'D0227', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Fatehabad (commercial vehicles only)', code: 'D0228', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Ferozepur Jhirka', code: 'D0229', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Ganaur', code: 'D0230', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Gohana', code: 'D0231', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Guhla', code: 'D0232', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Gurgaon', code: 'D0233', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Gurgaon (South)', code: 'D0234', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Gurgaon (commercial vehicles only)', code: 'D0235', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Hansi', code: 'D0236', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Hatin', code: 'D0237', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Hisar', code: 'D0238', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Hisar (commercial vehicles only)', code: 'D0239', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Hodal', code: 'D0240', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Indri', code: 'D0241', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Jagadhari', code: 'D0242', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Jhajjar', code: 'D0243', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Jhajjar (commercial vehicles only)', code: 'D0244', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Jind', code: 'D0245', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Jind (commercial vehicles only)', code: 'D0246', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Kaithal', code: 'D0247', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Kaithal (commercial vehicles only)', code: 'D0248', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Kalka', code: 'D0249', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Karnal', code: 'D0250', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Karnal (commercial vehicles only)', code: 'D0251', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Kharkhoda', code: 'D0252', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Kosli', code: 'D0253', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Kundli', code: 'D0254', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Kuru', code: 'D0255', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Kurukshetra (commercial vehicles only)', code: 'D0256', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Loharu', code: 'D0257', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Meham', code: 'D0258', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Mewat (Nuh)', code: 'D0259', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Mohindergarh', code: 'D0260', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Naraingarh', code: 'D0261', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Narnaul', code: 'D0262', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Narnaul (commercial vehicles only)', code: 'D0263', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Narwana', code: 'D0264', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Nuh', code: 'D0265', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Palwal', code: 'D0266', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Panchkula', code: 'D0267', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Panchkula (commercial vehicles only)', code: 'D0268', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Panipat', code: 'D0269', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Panipat (commercial vehicles only)', code: 'D0270', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Pataudi', code: 'D0271', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Pehowa', code: 'D0272', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Ratia', code: 'D0273', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Rewari', code: 'D0274', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Rewari (commercial vehicles only)', code: 'D0275', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Rohtak', code: 'D0276', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Rohtak (commercial vehicles only)', code: 'D0277', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Safidon', code: 'D0278', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Sahabad', code: 'D0279', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Samalkha', code: 'D0280', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Sirsa', code: 'D0281', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Sirsa (commercial vehicles only)', code: 'D0282', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Siwani', code: 'D0283', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Sonepat', code: 'D0284', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Sonipat', code: 'D0285', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Sonipat (commercial vehicles only)', code: 'D0286', state: 'Haryana', status: 'ACTIVE' },
  { name: 'This series belongs to the Transport Commissioner in Chandigarh', code: 'D0287', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Tohana', code: 'D0288', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Tosham', code: 'D0289', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Yamuna Nagar', code: 'D0290', state: 'Haryana', status: 'ACTIVE' },
  { name: 'Amb', code: 'D0291', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Anni', code: 'D0292', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Arki', code: 'D0293', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Baijnath', code: 'D0294', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Banjar', code: 'D0295', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Barsar', code: 'D0296', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Bharmour', code: 'D0297', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Bhoranj', code: 'D0298', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Bilaspur', code: 'D0299', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Chamba', code: 'D0300', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Chaupal', code: 'D0301', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Chowari', code: 'D0302', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Churah', code: 'D0303', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Dalhousie', code: 'D0304', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Dehra', code: 'D0305', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Dharamsala (autorikshaws)', code: 'D0306', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Dharamshala', code: 'D0307', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'DodraKwar', code: 'D0308', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Ghumarwin', code: 'D0309', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Hamirpur', code: 'D0310', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Jaisinghpur', code: 'D0311', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Jawali', code: 'D0312', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Jogindernagar', code: 'D0313', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Kalpa', code: 'D0314', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Kandaghat', code: 'D0315', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Kangra', code: 'D0316', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Karsog', code: 'D0317', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Kaza', code: 'D0318', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Keylong', code: 'D0319', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Kullu', code: 'D0320', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Manali', code: 'D0321', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Mandi', code: 'D0322', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Mandi (autorikshaws)', code: 'D0323', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Nadaun / Hamirpur', code: 'D0324', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Nahan', code: 'D0325', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Nalagarh', code: 'D0326', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Nichar (Bhaba Nagar)', code: 'D0327', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Nurpur', code: 'D0328', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Paddhar', code: 'D0329', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Palampur', code: 'D0330', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Pangi', code: 'D0331', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Paonta Sahib', code: 'D0332', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Parwanoo', code: 'D0333', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Pooh', code: 'D0334', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Rajgarh', code: 'D0335', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Rampur Bushar', code: 'D0336', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Rohru', code: 'D0337', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Sarkaghat', code: 'D0338', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Shimla', code: 'D0339', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Shimla  Urban', code: 'D0340', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Shimla  Urban (tourist buses & taxis)', code: 'D0341', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Shimla (autorikshaws)', code: 'D0342', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Shimla (rural)', code: 'D0343', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Solan', code: 'D0344', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Sundernagar', code: 'D0345', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Theog', code: 'D0346', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Udaipur', code: 'D0347', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Una', code: 'D0348', state: 'Himachal Pradesh', status: 'ACTIVE' },
  { name: 'Anantnag', code: 'D0349', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Bandipora', code: 'D0350', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Baramulla', code: 'D0351', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Budgam', code: 'D0352', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Doda', code: 'D0353', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Ganderbal', code: 'D0354', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Jammu', code: 'D0355', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Kargil', code: 'D0356', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Kathua', code: 'D0357', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Kishtwar', code: 'D0358', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Kulgam', code: 'D0359', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Kupwara', code: 'D0360', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Leh', code: 'D0361', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Poonch', code: 'D0362', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Pulwama', code: 'D0363', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Rajouri', code: 'D0364', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Ramban', code: 'D0365', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Reasi', code: 'D0366', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Samba', code: 'D0367', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Shopian', code: 'D0368', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Srinagar', code: 'D0369', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Udhampur', code: 'D0370', state: 'Jammu & Kashmir', status: 'ACTIVE' },
  { name: 'Bokaro Steel City', code: 'D0371', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Chaibasa', code: 'D0372', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Chatra', code: 'D0373', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Daltonganj', code: 'D0374', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Deoghar', code: 'D0375', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Dhanbad', code: 'D0376', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Dumka', code: 'D0377', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Garhwa', code: 'D0378', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Giridih', code: 'D0379', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Godda', code: 'D0380', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Gumla', code: 'D0381', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Hazaribagh / Ramgarh', code: 'D0382', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Jamshedpur', code: 'D0383', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Jamtara', code: 'D0384', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Koderma', code: 'D0385', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Latehar', code: 'D0386', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Lohardaga', code: 'D0387', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Pakur', code: 'D0388', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Ranchi', code: 'D0389', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Sahibganj', code: 'D0390', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'SaraikelaKharsawan', code: 'D0391', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Simdega', code: 'D0392', state: 'Jharkhand', status: 'ACTIVE' },
  { name: 'Bagalkot', code: 'D0393', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Bailhongal', code: 'D0394', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Bangalore Central (Koramangala)', code: 'D0395', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Bangalore East (Indiranagar)', code: 'D0396', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Bangalore North (Yeshwanthpur)', code: 'D0397', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Bangalore South (Jayanagar)]]', code: 'D0398', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Bangalore West (Rajajinagar)', code: 'D0399', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Basavakalyan', code: 'D0400', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Belgaum', code: 'D0401', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Bellary', code: 'D0402', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Bhalki', code: 'D0403', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Bidar', code: 'D0404', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Bijapur', code: 'D0405', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Chamrajnagar', code: 'D0406', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Chickmagalur', code: 'D0407', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Chikkaballapur', code: 'D0408', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Chikkodi', code: 'D0409', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Chitradurga', code: 'D0410', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Davangere', code: 'D0411', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Devanahalli', code: 'D0412', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Dharwad', code: 'D0413', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Electronics City', code: 'D0414', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Gadag', code: 'D0415', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Gokak', code: 'D0416', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Gulbarga', code: 'D0417', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Hassan', code: 'D0418', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Haveri', code: 'D0419', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Honnavar', code: 'D0420', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Hospet', code: 'D0421', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Hunsur', code: 'D0422', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Jamkhandi', code: 'D0423', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'K.R. Puram', code: 'D0424', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Karwar', code: 'D0425', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Kolar', code: 'D0426', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Kolar Gold Fields (KGF)', code: 'D0427', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Koppal', code: 'D0428', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Madikeri', code: 'D0429', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Mandya', code: 'D0430', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Mangalore', code: 'D0431', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Mysore East', code: 'D0432', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Mysore West', code: 'D0433', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Nagamangala', code: 'D0434', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Nelamangala', code: 'D0435', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Puttur / Sullia', code: 'D0436', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Raichur', code: 'D0437', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Rajarajeshwari Nagar', code: 'D0438', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Ramanagara', code: 'D0439', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Sagara', code: 'D0440', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Sakleshpur', code: 'D0441', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Shantinagar', code: 'D0442', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Shimoga', code: 'D0443', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Sirsi', code: 'D0444', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Tiptur', code: 'D0445', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Tumkur', code: 'D0446', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Udupi', code: 'D0447', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Yadgir', code: 'D0448', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Yelahanka', code: 'D0449', state: 'Karnataka', status: 'ACTIVE' },
  { name: 'Adoor', code: 'D0450', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Alappuzha', code: 'D0451', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Alathur', code: 'D0452', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Aluva', code: 'D0453', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Angamaly', code: 'D0454', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Chalakkudy', code: 'D0455', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Changanassery', code: 'D0456', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Chengannur', code: 'D0457', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Cherthala', code: 'D0458', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Eranakulam', code: 'D0459', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Guruvayur', code: 'D0460', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Idukki', code: 'D0461', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Irinjalakuda', code: 'D0462', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kanhangad', code: 'D0463', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kanjirappally', code: 'D0464', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kannur', code: 'D0465', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Karunagapally', code: 'D0466', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kasargode', code: 'D0467', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kayamkulam', code: 'D0468', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kazhakkoottam', code: 'D0469', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kodungallur', code: 'D0470', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Koduvally', code: 'D0471', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kollam', code: 'D0472', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kottarakara', code: 'D0473', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kottayam', code: 'D0474', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Koyilandi', code: 'D0475', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kozhikode', code: 'D0476', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kunnathur', code: 'D0477', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Malappuram', code: 'D0478', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Mallappally', code: 'D0479', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Mannarghat', code: 'D0480', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Mattancherry', code: 'D0481', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Mavelikara', code: 'D0482', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Muvattupuzha', code: 'D0483', state: 'Kerala', status: 'ACTIVE' },
  { name: 'North Paravur', code: 'D0484', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Ottappalam', code: 'D0485', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Pala', code: 'D0486', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Palakkad', code: 'D0487', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Pathanamthitta', code: 'D0488', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Pattambi', code: 'D0489', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Perinthalmanna', code: 'D0490', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Perumbavoor', code: 'D0491', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Ponnani', code: 'D0492', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Punalur', code: 'D0493', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Ranni', code: 'D0494', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Thalassery', code: 'D0495', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Thaliparamba', code: 'D0496', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Thirurangadi', code: 'D0497', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Thiruvalla', code: 'D0498', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Thiruvananthapuram (Kerala State Road Transport Corporation buses)', code: 'D0499', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Thiruvananthapuram City', code: 'D0500', state: 'Kerala', status: 'ACTIVE' },
  { name: 'ThiruvananthapuramAttingal', code: 'D0501', state: 'Kerala', status: 'ACTIVE' },
  { name: 'ThiruvananthapuramNedumangad', code: 'D0502', state: 'Kerala', status: 'ACTIVE' },
  { name: 'ThiruvananthapuramNeyyattinkara', code: 'D0503', state: 'Kerala', status: 'ACTIVE' },
  { name: 'ThiruvananthapuramParassala', code: 'D0504', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Thodupuzha', code: 'D0505', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Thripunithura', code: 'D0506', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Thrissur', code: 'D0507', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Tirur', code: 'D0508', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Vadakara', code: 'D0509', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Vaikom', code: 'D0510', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Vandiperiyar', code: 'D0511', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Wadakkancherry', code: 'D0512', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Wayanad', code: 'D0513', state: 'Kerala', status: 'ACTIVE' },
  { name: 'kothamangalam', code: 'D0514', state: 'Kerala', status: 'ACTIVE' },
  { name: 'Kavaratti', code: 'D0515', state: 'Lakshadweep', status: 'ACTIVE' },
  { name: '(not alloted)', code: 'D0516', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Alirajpur (upcoming)', code: 'D0517', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Ambikapur (not in use)', code: 'D0518', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Anoopur', code: 'D0519', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Ashoknagar', code: 'D0520', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Badwani', code: 'D0521', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Balaghat', code: 'D0522', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Betul', code: 'D0523', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Bhind', code: 'D0524', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Bhopal', code: 'D0525', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Bilaspur (not in use)', code: 'D0526', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Burhanpur', code: 'D0527', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Chhatarpur', code: 'D0528', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Chhindwara', code: 'D0529', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Damoh', code: 'D0530', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Datia', code: 'D0531', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Dewas', code: 'D0532', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Dhar', code: 'D0533', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Dindori', code: 'D0534', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Durg (not in use)', code: 'D0535', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Guna', code: 'D0536', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Gwalior', code: 'D0537', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Harda', code: 'D0538', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Hoshangabad', code: 'D0539', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Indore', code: 'D0540', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Jabalpur', code: 'D0541', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Jagdalpur (not in use)', code: 'D0542', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Jhabua', code: 'D0543', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Katni', code: 'D0544', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Khandwa', code: 'D0545', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Khargone', code: 'D0546', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'M.P. Government Vehicle', code: 'D0547', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'M.P. Police Vehicle', code: 'D0548', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Mandla', code: 'D0549', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Mandsaur', code: 'D0550', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Morena', code: 'D0551', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Narsinghpur', code: 'D0552', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Neemuch', code: 'D0553', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Panna', code: 'D0554', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Raipur (not in use)', code: 'D0555', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Raisen', code: 'D0556', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Rajgarh', code: 'D0557', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Rajnandgaon (not in use)', code: 'D0558', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Ratlam', code: 'D0559', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Rewa', code: 'D0560', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Sagar', code: 'D0561', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Satna', code: 'D0562', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Sehore', code: 'D0563', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Seoni', code: 'D0564', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Shahdol', code: 'D0565', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Shajapur', code: 'D0566', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Sheopur', code: 'D0567', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Shivpuri', code: 'D0568', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Sidhi', code: 'D0569', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Singrauli', code: 'D0570', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'State Governor\'s Vehicle', code: 'D0571', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Tikamgarh', code: 'D0572', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Ujjain', code: 'D0573', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Umariya', code: 'D0574', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Vidisha', code: 'D0575', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'not in use', code: 'D0576', state: 'Madhya Pradesh', status: 'ACTIVE' },
  { name: 'Ahmednagar', code: 'D0577', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Akluj', code: 'D0578', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Akola', code: 'D0579', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Ambejogai', code: 'D0580', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Amravati', code: 'D0581', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Aurangabad', code: 'D0582', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Baramati', code: 'D0583', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Beed', code: 'D0584', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Bhandara', code: 'D0585', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Borivali', code: 'D0586', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Buldana', code: 'D0587', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Chandrapur', code: 'D0588', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Dhule', code: 'D0589', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Gadchiroli', code: 'D0590', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Gondia', code: 'D0591', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Hingoli', code: 'D0592', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Jalgaon', code: 'D0593', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Jalna', code: 'D0594', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Karad (Satara Rural)  RTO is located in Karad', code: 'D0595', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Kolhapur', code: 'D0596', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Latur', code: 'D0597', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Malegaon', code: 'D0598', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Mumbai (Central)  RTO is located in Tardeo', code: 'D0599', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Mumbai (East)  RTO is located in Wadala', code: 'D0600', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Mumbai (West)  RTO is located in Andheri West', code: 'D0601', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Nagpur', code: 'D0602', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Nagpur (East)  RTO is located on Bhandara Road', code: 'D0603', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Nanded', code: 'D0604', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Nandurbar', code: 'D0605', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Nashik', code: 'D0606', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Navi Mumbai  RTO is located in Vashi (Sanpada)', code: 'D0607', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Osmanabad', code: 'D0608', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Panvel', code: 'D0609', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Parbhani', code: 'D0610', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Pune', code: 'D0611', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Pune (Outskirts)  RTO is located in PimpriChinchwad', code: 'D0612', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Raigad  RTO is located in Pen (does not include Navi Mumbai', code: 'D0613', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Ratnagiri', code: 'D0614', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Sangli', code: 'D0615', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Satara', code: 'D0616', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Shrirampur', code: 'D0617', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Sindhudurg', code: 'D0618', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Solapur', code: 'D0619', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Thane', code: 'D0620', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Thane (Central Suburbs): Kalyan', code: 'D0621', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Vasai Thane (Western Suburbs from Vasai)  RTO is located in Virar', code: 'D0622', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Wadi', code: 'D0623', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Wardha', code: 'D0624', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Washim', code: 'D0625', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Yavatmal  RTO is located on Nagpur Road', code: 'D0626', state: 'Maharashtra', status: 'ACTIVE' },
  { name: 'Churachandpur', code: 'D0627', state: 'Manipur', status: 'ACTIVE' },
  { name: 'Imphal', code: 'D0628', state: 'Manipur', status: 'ACTIVE' },
  { name: 'Kangpokpi', code: 'D0629', state: 'Manipur', status: 'ACTIVE' },
  { name: 'Thoubal', code: 'D0630', state: 'Manipur', status: 'ACTIVE' },
  { name: 'East Garo Hills', code: 'D0631', state: 'Meghalaya', status: 'ACTIVE' },
  { name: 'East Khasi Hills', code: 'D0632', state: 'Meghalaya', status: 'ACTIVE' },
  { name: 'Jaintia Hills', code: 'D0633', state: 'Meghalaya', status: 'ACTIVE' },
  { name: 'RiBhoi', code: 'D0634', state: 'Meghalaya', status: 'ACTIVE' },
  { name: 'Shillong (government vehicles)', code: 'D0635', state: 'Meghalaya', status: 'ACTIVE' },
  { name: 'Shillong (police vehicles)', code: 'D0636', state: 'Meghalaya', status: 'ACTIVE' },
  { name: 'Shillong (vehicles owned by transport corporations)', code: 'D0637', state: 'Meghalaya', status: 'ACTIVE' },
  { name: 'South Garo Hills', code: 'D0638', state: 'Meghalaya', status: 'ACTIVE' },
  { name: 'West Garo Hills', code: 'D0639', state: 'Meghalaya', status: 'ACTIVE' },
  { name: 'West Khasi Hills', code: 'D0640', state: 'Meghalaya', status: 'ACTIVE' },
  { name: 'Aizawl', code: 'D0641', state: 'Mizoram', status: 'ACTIVE' },
  { name: 'Champhai', code: 'D0642', state: 'Mizoram', status: 'ACTIVE' },
  { name: 'Kolasib', code: 'D0643', state: 'Mizoram', status: 'ACTIVE' },
  { name: 'Lawngtlai', code: 'D0644', state: 'Mizoram', status: 'ACTIVE' },
  { name: 'Lunglei', code: 'D0645', state: 'Mizoram', status: 'ACTIVE' },
  { name: 'Mamit', code: 'D0646', state: 'Mizoram', status: 'ACTIVE' },
  { name: 'Saiha', code: 'D0647', state: 'Mizoram', status: 'ACTIVE' },
  { name: 'Serchhip', code: 'D0648', state: 'Mizoram', status: 'ACTIVE' },
  { name: 'Dimapur', code: 'D0649', state: 'Nagaland', status: 'ACTIVE' },
  { name: 'Kohima', code: 'D0650', state: 'Nagaland', status: 'ACTIVE' },
  { name: 'Mokokchung', code: 'D0651', state: 'Nagaland', status: 'ACTIVE' },
  { name: 'Mon', code: 'D0652', state: 'Nagaland', status: 'ACTIVE' },
  { name: 'Phek', code: 'D0653', state: 'Nagaland', status: 'ACTIVE' },
  { name: 'Tuensang', code: 'D0654', state: 'Nagaland', status: 'ACTIVE' },
  { name: 'Wokha', code: 'D0655', state: 'Nagaland', status: 'ACTIVE' },
  { name: 'Zunheboto', code: 'D0656', state: 'Nagaland', status: 'ACTIVE' },
  { name: 'Angul', code: 'D0657', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Balasore', code: 'D0658', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Baragarh', code: 'D0659', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Bhadrak', code: 'D0660', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Bhubaneswar', code: 'D0661', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Bolangir', code: 'D0662', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Boudh', code: 'D0663', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Chandikhole', code: 'D0664', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Cuttack', code: 'D0665', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Debagarh', code: 'D0666', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Dhenkanal', code: 'D0667', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Gajapati', code: 'D0668', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Ganjam', code: 'D0669', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Jagatsinghpur', code: 'D0670', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Jharsuguda', code: 'D0671', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Kalahandi', code: 'D0672', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Kendarapara', code: 'D0673', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Keonjhar', code: 'D0674', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Koraput', code: 'D0675', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Malkangiri', code: 'D0676', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Mayurbhanj', code: 'D0677', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Nabarangpur', code: 'D0678', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Nayagarh', code: 'D0679', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Nuapada', code: 'D0680', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Phulabani', code: 'D0681', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Puri', code: 'D0682', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Rayagada', code: 'D0683', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Rourkela', code: 'D0684', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Sambalpur', code: 'D0685', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Sonepur', code: 'D0686', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Sundergarh', code: 'D0687', state: 'Orissa', status: 'ACTIVE' },
  { name: 'Karaikal', code: 'D0688', state: 'Pondicherry', status: 'ACTIVE' },
  { name: 'Mahe', code: 'D0689', state: 'Pondicherry', status: 'ACTIVE' },
  { name: 'Pondicherry', code: 'D0690', state: 'Pondicherry', status: 'ACTIVE' },
  { name: 'Yanam', code: 'D0691', state: 'Pondicherry', status: 'ACTIVE' },
  { name: 'Abohar', code: 'D0692', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Ajnala', code: 'D0693', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Amloh', code: 'D0694', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Amritsar', code: 'D0695', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Anandpur Sahib', code: 'D0696', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Baba Bakala', code: 'D0697', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Bagha Purana', code: 'D0698', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Balachaur', code: 'D0699', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Barnala', code: 'D0700', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Bassi Pathana', code: 'D0701', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Batala', code: 'D0702', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Bathinda', code: 'D0703', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Bhulath', code: 'D0704', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Budhlada', code: 'D0705', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Chamkaur Sahib', code: 'D0706', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Dasua', code: 'D0707', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Dera Baba Nanak', code: 'D0708', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Dera Bassi', code: 'D0709', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Dhar', code: 'D0710', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Dhuri', code: 'D0711', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Faridkot', code: 'D0712', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Fatehgarh Sahib', code: 'D0713', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Fazilka', code: 'D0714', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Ferozepur', code: 'D0715', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Garhshankar', code: 'D0716', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Gidderbaha', code: 'D0717', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Gurdaspur', code: 'D0718', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Hoshiarpur', code: 'D0719', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Jagraon', code: 'D0720', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Jaitu', code: 'D0721', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Jalalabad', code: 'D0722', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Jalandhar', code: 'D0723', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Jhunir / Sardulgarh', code: 'D0724', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Kapurthala', code: 'D0725', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Khadoor Sahib', code: 'D0726', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Khamano', code: 'D0727', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Khanna', code: 'D0728', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Kharar', code: 'D0729', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Lehra', code: 'D0730', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Ludhiana', code: 'D0731', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Malerkotla', code: 'D0732', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Malout', code: 'D0733', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Mansa', code: 'D0734', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Moga', code: 'D0735', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Mohali', code: 'D0736', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Moonak', code: 'D0737', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Mukerian', code: 'D0738', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Muktsar', code: 'D0739', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Nabha', code: 'D0740', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Nakodar', code: 'D0741', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Nangal', code: 'D0742', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Nawanshahr', code: 'D0743', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Nihal Singh Wala', code: 'D0744', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Pathankot', code: 'D0745', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Patiala', code: 'D0746', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Patran', code: 'D0747', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Patti', code: 'D0748', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Payal', code: 'D0749', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Phagwara', code: 'D0750', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Phillaur', code: 'D0751', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Raikot', code: 'D0752', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Rajpura', code: 'D0753', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Rampura Phul', code: 'D0754', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Ropar', code: 'D0755', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Samana', code: 'D0756', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Samrala', code: 'D0757', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Sangrur', code: 'D0758', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Shahkot', code: 'D0759', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Sultanpur Lodhi', code: 'D0760', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Sunam', code: 'D0761', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Talwandi Sabo', code: 'D0762', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Tappa Mandi', code: 'D0763', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Tarn Taran', code: 'D0764', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Taxis', code: 'D0765', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Zira', code: 'D0766', state: 'Punjab', status: 'ACTIVE' },
  { name: 'Ajmer', code: 'D0767', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Alwar', code: 'D0768', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Banswara', code: 'D0769', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Baran', code: 'D0770', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Barmer', code: 'D0771', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Beawar', code: 'D0772', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Bharatpur', code: 'D0773', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Bhilwara', code: 'D0774', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Bikaner', code: 'D0775', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Bundi', code: 'D0776', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Chittaurgarh', code: 'D0777', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Churu', code: 'D0778', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Dausa', code: 'D0779', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Dholpur', code: 'D0780', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Didwana', code: 'D0781', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Dungarpur', code: 'D0782', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Hanumangarh', code: 'D0783', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Jaipur', code: 'D0784', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Jaisalmer', code: 'D0785', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Jalore', code: 'D0786', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Jhalawar', code: 'D0787', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Jhunjhunu', code: 'D0788', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Jodhpur', code: 'D0789', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Karauli', code: 'D0790', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Kota', code: 'D0791', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Kotputli', code: 'D0792', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Nagaur', code: 'D0793', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Pali', code: 'D0794', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Pratapgarh', code: 'D0795', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Rajsamand', code: 'D0796', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Ramganj Mandi', code: 'D0797', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Rawhhuu', code: 'D0798', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Sawai Madhopur', code: 'D0799', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Sikar', code: 'D0800', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Sirohi', code: 'D0801', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Sri Ganganagar', code: 'D0802', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Tonk', code: 'D0803', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Udaipur', code: 'D0804', state: 'Rajasthan', status: 'ACTIVE' },
  { name: 'Gangtok', code: 'D0805', state: 'Sikkim', status: 'ACTIVE' },
  { name: 'Gyalshing', code: 'D0806', state: 'Sikkim', status: 'ACTIVE' },
  { name: 'Jorethang', code: 'D0807', state: 'Sikkim', status: 'ACTIVE' },
  { name: 'Mangan', code: 'D0808', state: 'Sikkim', status: 'ACTIVE' },
  { name: 'Ariyalur', code: 'D0809', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Attur', code: 'D0810', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Chengalpattu', code: 'D0811', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Chennai Central (Ayanavaram)', code: 'D0812', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Chennai East (Basin Bridge)', code: 'D0813', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Chennai North (Vyasarpadi)', code: 'D0814', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Chennai North East (Tondiarpet)', code: 'D0815', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Chennai South (Thiruvanmiyur)', code: 'D0816', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Chennai South East (Mandaveli)', code: 'D0817', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Chennai South West (Valasarawakkam)', code: 'D0818', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Chennai West (Anna Nagar)', code: 'D0819', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Chennai West (K.K. Nagar)', code: 'D0820', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Coimbatore (Central)', code: 'D0821', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Coimbatore (North)', code: 'D0822', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Coimbatore (South)', code: 'D0823', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Cuddalore', code: 'D0824', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Dharapuram', code: 'D0825', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Dharmapuri', code: 'D0826', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Dindigul', code: 'D0827', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Erode', code: 'D0828', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Gobichettipalayam', code: 'D0829', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Hosur', code: 'D0830', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Kanchipuram', code: 'D0831', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Karur', code: 'D0832', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Krishnagiri', code: 'D0833', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Kumbakonam', code: 'D0834', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Madurai (Central)', code: 'D0835', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Madurai (North)', code: 'D0836', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Madurai (South)', code: 'D0837', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Marthandam', code: 'D0838', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Meenambakkam', code: 'D0839', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Mettupalayam', code: 'D0840', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Nagapattinam', code: 'D0841', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Nagercoil', code: 'D0842', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Namakkal', code: 'D0843', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Perambalur', code: 'D0844', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Perundurai', code: 'D0845', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Pollachi', code: 'D0846', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Pudukottai', code: 'D0847', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Ramanathapuram', code: 'D0848', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Ranipet', code: 'D0849', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Salem (East)', code: 'D0850', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Salem (West)', code: 'D0851', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Sankagiri', code: 'D0852', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Sengundram', code: 'D0853', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Sivagangai', code: 'D0854', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Srirangam (Tiruchirapalli)', code: 'D0855', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'State Government Vehicles', code: 'D0856', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'State Transport Undertakings', code: 'D0857', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Tambaram', code: 'D0858', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Tenkasi', code: 'D0859', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Thanjavur', code: 'D0860', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Theni', code: 'D0861', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Thiruchengode', code: 'D0862', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Thiruvannamalai', code: 'D0863', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Tindivanam', code: 'D0864', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Tiruchirapalli', code: 'D0865', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Tirunelveli', code: 'D0866', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Tirupur (North)', code: 'D0867', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Tirupur (South)', code: 'D0868', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Tiruvallur', code: 'D0869', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Tiruvarur', code: 'D0870', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Tuticorin', code: 'D0871', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Uthagamandalam', code: 'D0872', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Vellore', code: 'D0873', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Villupuram', code: 'D0874', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Virudhunagar', code: 'D0875', state: 'Tamil Nadu', status: 'ACTIVE' },
  { name: 'Agartala', code: 'D0876', state: 'Tripura', status: 'ACTIVE' },
  { name: 'Kailashahar', code: 'D0877', state: 'Tripura', status: 'ACTIVE' },
  { name: 'Udaipura', code: 'D0878', state: 'Tripura', status: 'ACTIVE' },
  { name: 'Agra', code: 'D0879', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Aligarh', code: 'D0880', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Allahabad', code: 'D0881', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Almora (not longer in use)', code: 'D0882', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Ambedkar Nagar', code: 'D0883', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Auraiya', code: 'D0884', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Ayodhya', code: 'D0885', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Azamgarh', code: 'D0886', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Azamgarh for commercial vehicles', code: 'D0887', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Azamgarh for government vehicles', code: 'D0888', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Badaun', code: 'D0889', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Baghpat', code: 'D0890', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Bahraich', code: 'D0891', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Ballia', code: 'D0892', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Balrampur', code: 'D0893', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Banda', code: 'D0894', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Barabanki', code: 'D0895', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Bareilly', code: 'D0896', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Basti', code: 'D0897', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Bhadohi', code: 'D0898', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Bijnor', code: 'D0899', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Bulandshahr', code: 'D0900', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Chamoli (not longer in use)', code: 'D0901', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Chandauli', code: 'D0902', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Chitrakoot Dham (Karwi)', code: 'D0903', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Dehradun (not longer in use)', code: 'D0904', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Deoria', code: 'D0905', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Etah', code: 'D0906', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Etawah', code: 'D0907', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Etawah for government vehicles', code: 'D0908', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Faizabad', code: 'D0909', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Farrukhabad', code: 'D0910', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Fatehpur', code: 'D0911', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Firozabad', code: 'D0912', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Ghaziabad', code: 'D0913', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Ghazipur', code: 'D0914', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Gonda', code: 'D0915', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Gorakhpur for commercial vehicles', code: 'D0916', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Gorakhpur for government vehicles', code: 'D0917', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Gorakhpur for private vehicles', code: 'D0918', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Haldwani (not longer in useï¿½?)', code: 'D0919', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Hamirpur', code: 'D0920', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Hapur', code: 'D0921', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Hardoi', code: 'D0922', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Haridwar (not longer in use)', code: 'D0923', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Jalaun', code: 'D0924', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Jaunpur', code: 'D0925', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Jaunpur for taxis', code: 'D0926', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Jhansi', code: 'D0927', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Jhansi for government vehicles', code: 'D0928', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Jhansi for public transport', code: 'D0929', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Jyotiba Phule Nagar', code: 'D0930', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Kannauj', code: 'D0931', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Kanpur  Urban', code: 'D0932', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Kanpur CNG Vehicles', code: 'D0933', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Kanpur Dehat (rural)', code: 'D0934', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Kanpur Government Vehicles', code: 'D0935', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Kanshiram Nagar', code: 'D0936', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Kaushambi', code: 'D0937', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Kheri', code: 'D0938', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Lalitpur', code: 'D0939', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Lucknow', code: 'D0940', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Lucknow (when UP32 will be exhausted)', code: 'D0941', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Mahamaya Nagar', code: 'D0942', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Mahoba', code: 'D0943', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Mahoba for commercial vehicles', code: 'D0944', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Mahoba for government vehicles', code: 'D0945', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Mahrajganj', code: 'D0946', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Mainpuri', code: 'D0947', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Mathura', code: 'D0948', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Mau', code: 'D0949', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Meerut (UP15AT for taxis', code: 'D0950', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Mirzapur', code: 'D0951', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Moradabad', code: 'D0952', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Muzaffarnagar', code: 'D0953', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'NOIDA / Gautam Buddha Nagar', code: 'D0954', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Padrauna', code: 'D0955', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Pauri (not longer in use)', code: 'D0956', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Pilibhit', code: 'D0957', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Pithoragarh (not longer in use)', code: 'D0958', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Prabudh Nagar', code: 'D0959', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Pratapgarh', code: 'D0960', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Raebareli', code: 'D0961', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Raebareli for commercial vehicles', code: 'D0962', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Raebareli for government vehicles', code: 'D0963', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Rampur', code: 'D0964', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Saharanpur', code: 'D0965', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Sant Kabir Nagar', code: 'D0966', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Shahjahanpur', code: 'D0967', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Shrawasti', code: 'D0968', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Siddharth Nagar', code: 'D0969', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Sitapur', code: 'D0970', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Sonbhadra', code: 'D0971', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Sultanpur', code: 'D0972', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Tehri (not longer in use)', code: 'D0973', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Udham Singh Nagar (not longer in use)', code: 'D0974', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Unnao', code: 'D0975', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Unnao for commercial vehicles', code: 'D0976', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Uttarkashi (not longer in use)', code: 'D0977', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Varanasi', code: 'D0978', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'to be alloted', code: 'D0979', state: 'Uttar Pradesh', status: 'ACTIVE' },
  { name: 'Almora', code: 'D0980', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Bageshwar', code: 'D0981', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Chamoli', code: 'D0982', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Champawat', code: 'D0983', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Dehra Dun (UK07TC for taxis)', code: 'D0984', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Haridwar', code: 'D0985', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Nanital', code: 'D0986', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Pauri', code: 'D0987', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Pithoragarh', code: 'D0988', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Rudraprayag', code: 'D0989', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Tehri', code: 'D0990', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Udham Singh Nagar', code: 'D0991', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Uttarkashi', code: 'D0992', state: 'Uttarakhand', status: 'ACTIVE' },
  { name: 'Alipurduar (other than transport vehicles)', code: 'D0993', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Alipurduar (transport vehicles)', code: 'D0994', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Asansol (other than transport vehicles)', code: 'D0995', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Asansol (transport vehicles)', code: 'D0996', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Balurghat (other than transport vehicles)', code: 'D0997', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Balurghat (transport vehicles)', code: 'D0998', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Bankura (other than transport vehicles)', code: 'D0999', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Bankura (transport vehicles)', code: 'D1000', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Barasat (other than transport vehicles)', code: 'D1001', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Barasat (transport vehicles)', code: 'D1002', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Barrackpore (other than transport vehicles)', code: 'D1003', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Barrackpore (transport vehicles)', code: 'D1004', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Birbhum (other than transport vehicles)', code: 'D1005', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Birbhum (transport vehicles)', code: 'D1006', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Burdwan (other than transport vehicles)', code: 'D1007', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Burdwan (transport vehicles)', code: 'D1008', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Contai (other than transport vehicles)', code: 'D1009', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Contai (transport vehicles)', code: 'D1010', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Cooch Behar (other than transport vehicles)', code: 'D1011', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Cooch Behar (transport vehicles)', code: 'D1012', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Darjeeling (other than transport vehicles)', code: 'D1013', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Darjeeling (transport vehicles)', code: 'D1014', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Durgapur (other than transport vehicles)', code: 'D1015', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Durgapur (transport vehicles)', code: 'D1016', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Hooghly (other than transport vehicles)', code: 'D1017', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Hooghly (other than transport vehicles)  exhausted', code: 'D1018', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Hooghly (transport vehicles)', code: 'D1019', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Howrah  to be used', code: 'D1020', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Howrah (other than transport vehicles)', code: 'D1021', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Howrah (other than transport vehicles)  till WB14 K', code: 'D1022', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Howrah (transport vehicles)', code: 'D1023', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Jalpaiguri (other than transport vehicles)', code: 'D1024', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Jalpaiguri (transport vehicles)', code: 'D1025', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Kalimpong (other than transport vehicles)', code: 'D1026', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Kalimpong (transport vehicles)', code: 'D1027', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Kolkata  to be used', code: 'D1028', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Kolkata (goods carriages)', code: 'D1029', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Kolkata (passenger vehicles)', code: 'D1030', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Kolkata (private fourwheelers)', code: 'D1031', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Kolkata (tractors', code: 'D1032', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Kolkata (twowheelers)', code: 'D1033', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Kolkata (twowheelers)  exhausted', code: 'D1034', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Malda (other than transport vehicles)', code: 'D1035', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Malda (transport vehicles)', code: 'D1036', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Midnapur (other than transport vehicles)', code: 'D1037', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Midnapur (transport vehicles)', code: 'D1038', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Murshidabad (other than transport vehicles)', code: 'D1039', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Murshidabad (transport vehicles)', code: 'D1040', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Nadia (other than transport vehicles)', code: 'D1041', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Nadia (transport vehicles)', code: 'D1042', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Purulia (other than transport vehicles)', code: 'D1043', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Purulia (transport vehicles)', code: 'D1044', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Raiganj (other than transport vehicles)', code: 'D1045', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Raiganj (transport vehicles)', code: 'D1046', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Siliguri (other than transport vehicles)', code: 'D1047', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Siliguri (transport vehicles)', code: 'D1048', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'South 24 Parganas', code: 'D1049', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Tamluk (other than transport vehicles)', code: 'D1050', state: 'West Bengal', status: 'ACTIVE' },
  { name: 'Tamluk (transport vehicles)', code: 'D1051', state: 'West Bengal', status: 'ACTIVE' }
    ]

    console.log(`🌱 Inserting ${districts.length} districts from RTO data...`)
    await District.bulkCreate(districts, { ignoreDuplicates: true })

    const total = await District.count()
    console.log(`✅ Done! Total districts in DB: ${total}`)
    process.exit(0)
  } catch (err) {
    console.error('❌ Error:', err.message)
    process.exit(1)
  }
}

run()
